# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /home/ubuntu/my-simple-web-app
# hooks:
#   AfterInstall:
#     - location: scripts/start_server.sh
#       timeout: 300
#       runas: ubuntu

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-simple-web-app
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
